### ISSUE TITLE
is the default capture size good and also how many images are needed for training to pass to VPilot

### ISSUE THREAD

**Issue by monajalal** [ai-tor/DeepGTAV#11]
So, I wonder if the default image width/height is good(realistic) for deep learning frameworks to detect objects? And what order of images should I collect to get ready for connecting to Vpilot?
This is my config.ini:
```

[common]
mode=0
imageWidth=320
imageHeight=160
car=0
weatherChangeDelay=300
initialWeather=-1
initialHour=-1
initialMinute=-1
initialPosX=-1
initialPosY=-1
maxDuration=1

[supervised]
setSpeed=15.0
drivingStyle=0
captureFreq=10
datasetDir=D:\DeepGTAV_dataset\

[reinforcement]
reward=2
desiredSpeed=15.0
desiredAgressivity=0.5
host=144.92.237.238
port=8000

```

possibly silly but is host referring to the one that VPilot is (Linux machine)?
and I saw in one post you were saying something regarding reward=1 or 2, what's the difference?
Also sometimes the camera has a side view, sometimes frontal view. Can that be fixed to always be frontal or side view? https://www.instagram.com/p/BPbxZpvD56d/?taken-by=mona_of_green_gables

**Comment by ai-tor** [comment]
Hi Mona,

It should be enough, this is the size comma.ai is using, so hopefully it will be! The area of the images is more or less the same used by AlexNet for the ImageNet challenge, and it worked like a charm!

I don't have an exact number of images needed to successfully train a self-driving agent, of course, the more the better, but I think at least 500000.

Finally, yes, the host indicates the IP of the machine where you run VPilot or any other agent. The details of the reward function are detailed in the README file.

Regarding the camera view, if the camera stops pointing front then it means the script stopped working, probably because it crashed. It should not! 👎 

Cheers!

**Comment by monajalal** [comment]
I restarted the game as the camera started showing back of the car but I wonder why it happens and how to fix it. It totally make sense to me why need the camera to face to the front of car as you need those images for detecting objects and driving in VPilot for RL. If you come across a fix for camera, please do update us. Thanks!

**Comment by ai-tor** [comment]
Hi Mona, 

It is not happening to me and I don't know how to reproduce the error. Could you share your ScriptHook log file?
