### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by muaz-git** [ai-tor/DeepGTAV#44]
Hello @ai-tor, nice work.
I have few questions. As I am currently analyzing this repository in order to figure out the aim for my master's thesis, which is why I haven't bought the game as well as tried your code. So I was wondering:

- If it is possible to have semantically labelled ground truth in dataset collection mode? 
- If your code works for steam version of the game as well?

It would be great if you could answer my questions. Thank you.

**Comment by ai-tor** [comment]
Hi @muaz-git

The answers are No and Yes in this order. Segmentation is not possible right now as IT requires to access the internal graphic buffers to match layers of textures with object types. Although this is possible to do, I don't have time to implement this due to other projects. 

Regarding the steam version, yeah, it should work like the standalone version, I've successfully work with both of them, setup is the same.
