### ISSUE TITLE
Exceptions when run the code

### ISSUE THREAD

**Issue by kenyxjp** [ai-tor/DeepGTAV#47]
1. I've run GTA5 and drive.py,but I got a problem as follows:
![image](https://cloud.githubusercontent.com/assets/10105415/26762675/bb23518e-4978-11e7-9e23-73b9385c9b1d.png)

2. I've download DeepGTAV and copy it to 'Grand Theft Auto V' directory as follows,is this a problem?
![image](https://cloud.githubusercontent.com/assets/10105415/26762665/9fccbf7e-4978-11e7-8ead-6462c0f8eb4e.png)

**Comment by ai-tor** [comment]
Hi! 

You should use Python 3

python3 drive.py

**Comment by ai-tor** [comment]
After the last update, bash should automatically pick up the correct Python version

`sudo chmod +x drive`
`./drive`

**Comment by AaronLeong** [comment]
I get the same problem today,but it can work last week!

**Comment by Creekee** [comment]
I met the same problem and it is not the problem of version of python.

**Comment by ai-tor** [comment]
Hey!

Can someone translate for me what the last line is saying? :)

**Comment by WenchaoDing** [comment]
Hi @ai-tor ,
The last line is as following,
Socket is not connected.
A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using sendto) no address was supplied.

**Comment by ai-tor** [comment]
Thanks @WenchaoDing,

Actually the problem comes much before that, when trying to send the Start command, Python internally converts an int to an array of bytes, which with Python 3.2 and above is done with the .to_bytes method. It looks like that your Python version somehow doesn't provide that method, maybe because the version is < 3.2

**Comment by Creekee** [comment]
Thanks @ai-tor ,
Actually I am using the latest version of python(3.6), so can you point the very code that may cause such a problem.

**Comment by ai-tor** [comment]
Hi Creekee, my mistake, I've looked further into the error, the primary reason it is not working is because the Python client is not able to connect to DeepGTAV. The following exception in client.py is catched:

```
try:
            self.s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self.s.connect((ip, int(port)))
        except:
            print('ERROR: Failed to connect to DeepGTAV') # <-- Here
        else:
            print('Successfully connected to DeepGTAV')
```
So this could be to several reasons:

1. The IP is not correctly set (it should point to the PC running DeepGTAV)
2. The port is not correctly set (by default it should be 8000)
3. DeepGTAV is not running. Make sure you got into story mode and that you have control over the player.
4. Somehow DeepGTAV is not able to open port 8000 (maybe it is being used by another application or the game has no rights)

Can you check this points? Thanks! :smile:

**Comment by Creekee** [comment]
Hi ai-tor 
Thanks for your help. But I didn't get it very well. Can you give me more details of setting up the IP and the port. Also how can I get to know whether is DeepGTAV running.
Best wishes.

**Comment by ai-tor** [comment]
Hi @Creekee,

If there isn't any error (warning window) DeepGTAV should automatically start running by entering the history mode. It will wait for the message from VPilot in the background.

If you have GTAV running in a Windows machine with IP '192.168.1.2' for instance, and VPilot executing in another machine, you should set there the client IP parameter to be  '192.168.1.2' and port 8000 (default DeepGTAV port), and of course, make sure you are in the same network.

You can also check Windows netstat to see if DeepGTAV is listening on port 8000 and also take a look at _deepgtav.log_ under your GTAV installation directory to check if there was any issue during initialization.
