### ISSUE TITLE
Width calculation

### ISSUE THREAD

**Issue by Jadore122** [ai-tor/DeepGTAV#48]
Hi @ai-tor ,

Nice to meet you!
Recently, I am interested in GTAV, and in the Github, I found your good job “DeepGTAV”, I appreciate it.
But I have some questions with your project, I sincerely hope you can kindly help me to give me some advice.

Some questions are described as following:
1.	In this link https://github.com/ai-tor/DeepGTAV/issues/8, you said that “A parameter called Width in paths.xml indicates whether the node falls just in the middle of a lane or in a line. ”
Could you give me a little more details how to know any node falls in the middle of a lane or in a line, for example, Width = 6, or Width = 1, or Width = -10, ……

2.	Still in the above link, I found one sentence “You are right, the width somehow indicates the width of the center "useless" lane.” 
Where, what is the meaning of “ the center "useless" lane”?
In addition, what is the right meaning of the “Width”, which indicates the node falls just in the middle of a lane or in a line, or the width of the center "useless" lane.?

3.	By the way, as to the file format of the node.ynd, do you know more node information, except for areaID, nodeID, linkID, node position.
For instance, do you know which bytes indicate the nodetype, density, flags, etc.

Thank you so much, in advance:)
Have a nice everyday!

**Comment by ai-tor** [comment]
Hi @Jadore122!

Nice to meet you too! :smile: 

This is a super "in research" topic, I made some discoveries myself but there is still a lot to figure out, I'll try to describe you what I know so far and see if we can make any more progress:

1.  So, "generally", the relation between node falling in the center of a lane or falling in a lane line and the width node attribute goes as follows: If width is positive, the node falls in the lane center, otherwise it falls in a lane line, except the case when LanesOut is 0 and LanesIn is not multiple of 2, in that case it also falls in the lane center. This is a solution I found by trial and error that works for a number of roads, but I believe there must be some kind of simpler rule that has to work for all GTAV roads. I would like to figure that out :smiley: 

2. I am referring to roads that for example have two lanes and then usually "yellow" region between them where vehicles are not supposed to drive. Follow the link for an example: https://thumbs.dreamstime.com/x/yellow-line-traffic-sign-15849595.jpg. 
Regarding the width, it seems that its magnitude could indicate the width of that "yellow" region too.

3. I've never opened that node.ynd. Have you? I don't know the order of the bytes, I only know their meaning, so I can't associate them for now

```
typedef struct {
	bool disabled; //Disabled (0)
	bool water; //Water (0)
	int speed; //Speed (4)
	int special; //Special (0)
	int density; //Density (-1)
	bool highway; //Highway (0)
	bool noGPS; //NoGps (0)
	bool tunnel; //Tunnel (0)
	bool cantGoLeft; //Cannot Go Left (0)
	bool leftTurnsOnly; //Left Turns Only (0)
	bool offRoad; //Off Road (0)
	bool cantGoRight; //Cannot Go Right (0)
	bool noBigVehicles; //No Big Vehicles (0)
	bool indicateKeepLeft; //Indicate Keep Left (0)
	bool indicateKeepRight; //Indicate Keep Right (0) 
	bool slipLane; //Slip Lane (0)
} tNodeAttr;

typedef struct {
	int width; //Width (0)
	int lanesIn; //Lanes In (1) 
	int lanesOut; //Lanes Out (1) 
	bool narrowRoad; //Narrowroad (0)
	bool gpsBothWays; //GpsBothWays (0)
	bool blockIfNoLanes; //Block If No Lanes (0)
	bool shortcut; //Shortcut (0)
	bool dontUseForNavigation; //Dont Use For Navigation (0)
} tLinkAttr;
```

**Comment by IanKirwan** [comment]
Great info. Sorry to see that it was not acknowledged before.
