### ISSUE TITLE
offset/lane reward calculation

### ISSUE THREAD

**Issue by tyluckyma** [ai-tor/DeepGTAV#8]
Hi @ai-tor 

Happy Christmas! Hope this message did not bother your holiday.

I'm now at the reinforcement learning part, and kind of stuck in the lane reward calculation. May I have your advice on the following questions:

1. May I ask how you find out the lane width? And how many lanes does road have?

2. Your lane reward calculation is a bit complicated than I expected, but seems to be well designed. May I ask have you considered the multi-lane road? Because the node coord is in the center of the road, so how you deal with roads that have 5 lanes (3 backward, 2 farward), or some imbalanced 4 lanes (3 backward, 1 forward).

3. Another thing is about the "GET_CLOSEST_ROAD" in scripthookV, I think it may help a bit, but cannot figure out how it works, any idea on this?

4. The command "PATHFIND::GET_NTH_CLOSEST_VEHICLE_NODE_ID(a_7_nodeCoord, 1, v_21_nodeType, 0x40400000, 0);" is usually finished with (0x40400000, 0), but I notice in your lane reward it is (300, 300). Does it mean the search range of the GET method, say like 300 meters x 300 meters range?

5. What are the differences between tNode and linePoint? Do they have same coordinates?

**Comment by tyluckyma** [comment]
Ooops, I overlooked that you loaded the path.xml. 

In case the difference in the game versions. I downloaded OpenIV and extracted mine from "GTAPath\common.rpf\data\levels\gta5\paths.xml"

Awesome man, I was wondering how did you know this file have the required information? I've tried on Google but find limited clues.

**Comment by ai-tor** [comment]
Hi @tyluckyma ,

Sorry for the delay in the response! I have been away of the computer during holidays. :)

As you have discovered, I took _paths.xml_ to retrieve information about the game's nodes. As you, I also looked in Google, but nobody had done this before, so I had to reverse engineer the game myself. Finding the nodes with OpenIV was a really important step! Then all I had to do is understand what it contained and how I could get the information I needed (lane width, number of lanes and direction of traffic). I will answer your questions now one by one:

1. The lane width depends on a number of factors, but basically I have found 3 widths used in all the game: 6.0 for highways, 4.2 for narrow roads and 5.5 for default roads. _paths.xml_ contains flags indicating if a node is in a highway on in a narrow road, so the width of the lane can be inferred from that. For the number of lanes, there are two values indicating that: LanesIn (number of lanes in the same direction of the node) and LanesOut (number of lanes in the reverse direction).

2. Yup! You got to the tricky part. What you need to do is to know is that the node is not always at the center of the road :). I also believe that at the beginning, but when I tried it I realized that this was not the case, in urban scenarios it failed most of the times. Actually, if the node is always in the center and you know the total number of lanes and their width, it is quite with some basic math to locate where the lines are, but as I said, this doesn't work. There is another parameter called Width in _paths.xml_ that although its confusing name it indicates whether the node falls just in the middle of a lane or in a line. So knowing that you can start calculating your line points starting from an offset (laneWidth/2) or from 0. You will have LanesIn + 1 points in the right of the node, and LanesOut + 1 points in the left of the node. See the setLinePoints method in the LaneRewarder method.

3. I would say it returned nodes in the center of a road, but anything more. Never found a useful way of using it.

4. I have tried different numbers for that parameters, but I never noticed any difference. 300,300 worked for me so I just use these :)

5. A tNode is just an struct encapsulating a game node, which has a location and some properties, like the ones I explained before. A linePoint is the result of applying 2 to a tNode, it is a point located on a lane line. So no! They don't have the same coordinates :)

Once you have the linePoints for the closest node, it is super easy to compute how far you are from the center of the lane. You just need to take the closest two pair of  linePoints and calculate the center of the lane and see how far is your vehicle from it. 

Hope this helps!

**Comment by tyluckyma** [comment]
Ooops, good to have your response!

I just notice the trick today. But still not very clear about that. For example, I've checked some links with "Width = 1-2". Their nodes are kinds of still on the line. When I tried width = 3, I started to think about the "width" somehow reflects the width of the center road (the useless road). 

But when I reach the one with "Width = 8-9", the center road width is somehow similar to those with 4. Any idea?

**Comment by tyluckyma** [comment]
Ahh, found a bit clue. Those roads actually have "kind of overlapped" links. The "hidden" link has laneout=0.

**Comment by ai-tor** [comment]
Hi @tyluckyma ,

Sorry for the late response. You are right, the width somehow indicates the widht of the center "useless" lane. The density indicates how many cars are usually travelling through that node. So in theory, highways should have high density and secondary roads almost 0, never tested that though.

I got the widths of the lanes by pure experimentation, looked like these values worked for most of the roads, but it is possible that I am missing some roads as you see :)

Hope you are lucky "decrypting" all this info!

**Comment by xiaoli-chen** [comment]
I found PATHFIND::GET_NTH_CLOSEST_VEHICLE_NODE_ID(node.coord.x, node.coord.y, node.coord.z, 1, 1, 300, 300); for some nodes it will return same ID ,
so sometime node.id will be duplicated.

**Comment by IanKirwan** [comment]
@tyluckyma  and @aitorzip 
I found paths.xml very difficult to use since the nodes are not really linked to each other in this file. I also realised that the large size of the file makes it slow to load, and figured it would be more logical to follow the same kind of ideas used in real mapping and navigation i.e. to break the world up into grids and only load the grid(s) revelvant to you at the point required.  It turns out that GTA V path map data is actually organized this way. Los Santos is divided up into grid squares each 1km x 1km (if my memory serves me correctly, though posibly 500m squares) as shown in the image below (which I grabbed from Codewalker). The path data for each grid square is stored within the game rpf files under `common.rpf\x64e.rpf\levels\gta5\paths.rpf` as ynd files. Using the RPF explorer in CodeWalker (version 30 onward I believe) you can right click on the ynd files and save them as xml. Each file is called nodes***n***.ynd where 'n' is the grid square ID. The nodes in these files are properly linked i.e. each node contains links to the previous and next nodes (or more if it is a junction) belonging to its path. The flag info is also there. Lane width and count info doesnt appear to be in these files which is unfortunate, but I think these files are better for navigation than paths.xml.

![GTA V map grid](https://vignette.wikia.nocookie.net/gtawiki/images/8/8f/Gridsquares.png "GTA V map grid")
Note: The grid squares on the bottom right, apparently in the sea somewhere, are in fact Ludendorf, from the story mode.

Hope its useful to someone other than me.
